export const resources = [
  {
    id: 1,
    name: "HSC",
    link: "hsc",
    sheet: 88,
    image: "/images/HSC_1741760933388.jpeg",
    category: "academic",
    tag: [],
  },
  {
    id: 2,
    name: "৯ম-১০ম শ্রেণি",
    link: "ssc",
    sheet: 44,
    image: "/images/icon_ssc.jpeg",
    category: "academic",
    tag: [],
  },
  {
    id: 3,
    name: "৮ম শ্রেণি",
    link: "c8",
    sheet: 51,
    image: "/images/icon_class8.jpeg",
    category: "academic",
    tag: [],
  },
  {
    id: 4,
    name: "৭ম শ্রেণি",
    link: "c7",
    sheet: 51,
    image: "/images/icon_class7.jpeg",
    category: "academic",
    tag: [],
  },
  {
    id: 5,
    name: "৬ষ্ঠ শ্রেণি",
    link: "c6",
    sheet: 21,
    image: "/images/icon_class6.jpeg",
    category: "academic",
    tag: [],
  },
];

export const courses = [
  {
    id: 1,
    title: "English Basic Spoken Course",
    authorized: "আরিফুল ইসলাম মানিক",
    price: "৯৯৯",
    listPrice: "১২৩৩",
    image: "/images/IMG_20250513_141238.jpg",
    category: "Board",
    tag: [],
  },
  {
    id: 2,
    title: "ক্লাস ৬ - SSC '30",
    authorized: "আরিফুল ইসলাম মানিক",
    price: "৩০০০",
    listPrice: "৩৯৯৯",
    image: "/images/sgfoxkd0w3zfrf2r7y0s.jpeg",
    category: "Academic",
    tag: ["six"],
  },
  {
    id: 3,
    title: "ক্লাস ৬ - SSC '30",
    authorized: "আরিফুল ইসলাম মানিক",
    price: "৩০০০",
    listPrice: "৩৯৯৯",
    image: "/images/sgfoxkd0w3zfrf2r7y0s.jpeg",
    category: "Academic",
    tag: ["six"],
  },
  {
    id: 4,
    title: "ক্লাস ৬ - SSC '30",
    authorized: "আরিফুল ইসলাম মানিক",
    price: "৩০০০",
    listPrice: "৩৯৯৯",
    image: "/images/sgfoxkd0w3zfrf2r7y0s.jpeg",
    category: "Animated",
    tag: ["six"],
  },
  {
    id: 5,
    title: "ক্লাস ৬ - SSC '30",
    authorized: "আরিফুল ইসলাম মানিক",
    price: "৩০০০",
    listPrice: "৩৯৯৯",
    image: "/images/sgfoxkd0w3zfrf2r7y0s.jpeg",
    category: "Animated",
    tag: ["ten", "admission"],
  },
  {
    id: 6,
    title: "ক্লাস ৬ - SSC '30",
    authorized: "আরিফুল ইসলাম মানিক",
    price: "৩০০০",
    listPrice: "৩৯৯৯",
    image: "/images/sgfoxkd0w3zfrf2r7y0s.jpeg",
    category: "Academic",
    tag: ["hsc", "admission"],
  },
  {
    id: 7,
    title: "ক্লাস ৬ - SSC '30",
    authorized: "আরিফুল ইসলাম মানিক",
    price: "৩০০০",
    listPrice: "৩৯৯৯",
    image: "/images/sgfoxkd0w3zfrf2r7y0s.jpeg",
    category: "Academic",
    tag: ["nine", "admission"],
  },
  {
    id: 8,
    title: "ক্লাস ৬ - SSC '30",
    authorized: "আরিফুল ইসলাম মানিক",
    price: "৩০০০",
    listPrice: "৩৯৯৯",
    image: "/images/sgfoxkd0w3zfrf2r7y0s.jpeg",
    category: "Academic",
    tag: ["eight", "admission"],
  },
  {
    id: 9,
    title: "ক্লাস ৬ - SSC '30",
    authorized: "আরিফুল ইসলাম মানিক",
    price: "৩০০০",
    listPrice: "৩৯৯৯",
    image: "/images/sgfoxkd0w3zfrf2r7y0s.jpeg",
    category: "Academic",
    tag: ["seven", "admission"],
  },
];
